export enum ExceptionMessageCode {
  // JWT
  JWT_INVALID_PAYLOAD = 'JWT_INVALID_PAYLOAD',
  JWT_INVALID_PLATFORM = 'JWT_INVALID_PLATFORM',
  JWT_INVALID_USERID = 'JWT_INVALID_USERID',
  MISSING_TOKEN = 'MISSING_TOKEN',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  REFRESH_EXPIRED_TOKEN = 'REFRESH_EXPIRED_TOKEN',
  ACCESS_EXPIRED_TOKEN = 'ACCESS_EXPIRED_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  NOT_BEFORE_CLAIM_TOKEN = 'NOT_BEFORE_CLAIM_TOKEN',
  REFRESH_TOKEN_REUSE = 'REFRESH_TOKEN_REUSE',

  // Auth
  RECOVER_PASSWORD_REQUEST_NOT_FOUND = 'RECOVER_PASSWORD_REQUEST_NOT_FOUND',
  RECOVER_PASSWORD_REQUEST_INVALID = 'RECOVER_PASSWORD_REQUEST_INVALID',
  RECOVER_PASSWORD_REQUEST_TIMED_OUT = 'RECOVER_PASSWORD_REQUEST_TIMED_OUT',
  RECOVER_PASSWORD_TOKEN_REUSE = 'RECOVER_PASSWORD_TOKEN_REUSE',

  RESET_PASSWORD_REQUEST_NOT_FOUND = 'RESET_PASSWORD_REQUEST_NOT_FOUND',
  RESET_PASSWORD_REQUEST_INVALID = 'RESET_PASSWORD_REQUEST_INVALID',
  RESET_PASSWORD_REQUEST_TIMED_OUT = 'RESET_PASSWORD_REQUEST_TIMED_OUT',
  RESET_PASSWORD_TOKEN_REUSE = 'RESET_PASSWORD_TOKEN_REUSE',

  ACCOUNT_VERIFICATION_REQUEST_NOT_FOUND = 'ACCOUNT_VERIFICATION_REQUEST_NOT_FOUND',
  ACCOUNT_VERIFICATION_REQUEST_INVALID = 'ACCOUNT_VERIFICATION_REQUEST_INVALID',
  ACCOUNT_VERIFICATION_REQUEST_TIMED_OUT = 'ACCOUNT_VERIFICATION_REQUEST_TIMED_OUT',
  ACCOUNT_VERIFICATION_TOKEN_REUSE = 'ACCOUNT_VERIFICATION_TOKEN_REUSE',

  // Main
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',
  USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',
  USER_LOCKED = 'USER_LOCKED',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_IDENTITY_NOT_FOUND = 'USER_IDENTITY_NOT_FOUND',

  LEGAL_DOCUMENT_NOT_FOUND = 'LEGAL_DOCUMENT_NOT_FOUND',
  LEGAL_DOCUMENT_PARAGRAPH_NOT_FOUND = 'LEGAL_DOCUMENT_PARAGRAPH_NOT_FOUND',

  // Other
  EMAIL_OR_PASSWORD_INVALID = 'EMAIL_OR_PASSWORD_INVALID',
  MISSING_CURRENT_USER_PAYLOAD = 'MISSING_CURRENT_USER_PAYLOAD',
  PASSWORD_INVALID = 'PASSWORD_INVALID',
  NEW_PASSWORD_SAME = 'NEW_PASSWORD_SAME',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',
}
